name: mlflow-env
channels:
  - conda-forge # Added conda-forge for broader package availability
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - mlflow
      - pandas
      - scikit-learn
      - numpy
      - matplotlib
      - seaborn
      - ipykernel
      - jupyterlab
      - mamba
