name: CI - MLflow Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Conda (with Mamba)
        uses: goanpeca/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          activate-environment: mlflow-env
          environment-file: ./mlproject/conda.yaml
          use-mamba: true

      - name: Check conda environment
        run: conda list

      - name: Install MLflow CLI (ensure available in PATH)
        run: pip install mlflow

      # Optional: install additional Python dependencies (if any)
      - name: Install additional Python dependencies
        run: pip install -r ./mlproject/requirements.txt

      - name: Run MLflow Project
        run: |
          mlflow run ./mlproject --env-manager=local --experiment-name "student-performance-classification"

      - name: Upload model artefacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: ./mlruns
