name: CI - MLflow Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install conda
        uses: goanpeca/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.10
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          use-mamba: true

      - name: Check environment
        run: conda list

      - name: Set MLflow Tracking URI
        run: echo "MLFLOW_TRACKING_URI=http://127.0.0.1:5000" >> $GITHUB_ENV

      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=conda --experiment-name "student-performance-classification"

      - name: Upload model artefacts to repo
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: ./mlruns
